### ISSUE TITLE
Can't find deepgram api key

### ISSUE THREAD

**Issue by DrewPear309** [xRiddin/Real-Time-AI-Voice-Assistant#1]
c:\real>npm run start

> AI Voice Assistant@1.1.0 start
> node server.js

c:\real\node_modules\@deepgram\sdk\dist\main\packages\AbstractClient.js:23
            throw new errors_1.DeepgramError("A deepgram API key is required");
            ^

DeepgramError: A deepgram API key is required
    at new AbstractClient (c:\real\node_modules\@deepgram\sdk\dist\main\packages\AbstractClient.js:23:19)
    at new DeepgramClient (c:\real\node_modules\@deepgram\sdk\dist\main\DeepgramClient.js:16:1)
    at createClient (c:\real\node_modules\@deepgram\sdk\dist\main\index.js:40:12)
    at Object.<anonymous> (c:\real\server.js:35:24)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  __dgError: true
}

Node.js v21.7.1

**Comment by moskanoro** [comment]
> c:\real>npm run start
> 
> > AI Voice Assistant@1.1.0 start
> > node server.js
> 
> c:\real\node_modules@deepgram\sdk\dist\main\packages\AbstractClient.js:23 throw new errors_1.DeepgramError("A deepgram API key is required"); ^
> 
> DeepgramError: A deepgram API key is required at new AbstractClient (c:\real\node_modules@deepgram\sdk\dist\main\packages\AbstractClient.js:23:19) at new DeepgramClient (c:\real\node_modules@deepgram\sdk\dist\main\DeepgramClient.js:16:1) at createClient (c:\real\node_modules@deepgram\sdk\dist\main\index.js:40:12) at Object. (c:\real\server.js:35:24) at Module._compile (node:internal/modules/cjs/loader:1368:14) at Module._extensions..js (node:internal/modules/cjs/loader:1426:10) at Module.load (node:internal/modules/cjs/loader:1205:32) at Module._load (node:internal/modules/cjs/loader:1021:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) at node:internal/main/run_main_module:28:49 { __dgError: true }
> 
> Node.js v21.7.1

make sure to put the api key in ur .env file 
and install the deepgram sdk : npm install @deepgram/sdk
