### ISSUE TITLE
WebSocket Connection issue 

### ISSUE THREAD

**Issue by moskanoro** [xRiddin/Real-Time-AI-Voice-Assistant#2]
$ npm run start

> AI Voice Assistant@1.1.0 start
> node server.js

playht: initializing
(node:67904) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server is listening on port 3000
socket: client connected
null
socket: data couldn't be sent to deepgram
deepgram: connected
deepgram: packet received
deepgram: metadata received
ws: metadata sent to client
deepgram: disconnected
C:\Users\mosta\Downloads\Real-Time-AI-Voice-Assistant-main-89899\Real-Time-AI-Voice-Assistant-main\node_modules\websocket\lib\W3CWebSocket.js:111
        throw new Error('cannot call send() while not connected');
              ^

Error: cannot call send() while not connected
    at W3CWebSocket.send (C:\Users\mosta\Downloads\Real-Time-AI-Voice-Assistant-main-89899\Real-Time-AI-Voice-Assistant-main\node_modules\websocket\lib\W3CWebSocket.js:111:15)
    at LiveClient.finish (C:\Users\mosta\Downloads\Real-Time-AI-Voice-Assistant-main-89899\Real-Time-AI-Voice-Assistant-main\node_modules\@deepgram\sdk\dist\main\packages\LiveClient.js:104:22)
    at LiveClient.<anonymous> (C:\Users\mosta\Downloads\Real-Time-AI-Voice-Assistant-main-89899\Real-Time-AI-Voice-Assistant-main\server.js:130:16)
    at LiveClient.emit (node:events:520:28)
    at LiveClient._socket.onclose (C:\Users\mosta\Downloads\Real-Time-AI-Voice-Assistant-main-89899\Real-Time-AI-Voice-Assistant-main\node_modules\@deepgram\sdk\dist\main\packages\LiveClient.js:24:18)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\mosta\Downloads\Real-Time-AI-Voice-Assistant-main-89899\Real-Time-AI-Voice-Assistant-main\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Users\mosta\Downloads\Real-Time-AI-Voice-Assistant-main-89899\Real-Time-AI-Voice-Assistant-main\node_modules\websocket\lib\W3CWebSocket.js:228:10)      
    at WebSocketConnection.<anonymous> (C:\Users\mosta\Downloads\Real-Time-AI-Voice-Assistant-main-89899\Real-Time-AI-Voice-Assistant-main\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:520:28)
    at WebSocketConnection.handleSocketClose (C:\Users\mosta\Downloads\Real-Time-AI-Voice-Assistant-main-89899\Real-Time-AI-Voice-Assistant-main\node_modules\websocket\lib\WebSocketConnection.js:389:14)

Node.js v22.2.0

**Comment by webbrain-one** [comment]
Hi! Thanks for reporting this. I opened PR #4, which fixes the WebSocket crash by preventing the server from calling Deepgram’s `send()`/`finish()` after the underlying socket has already disconnected. It adds a safe check so closing or dropping a connection won’t throw `cannot call send() while not connected`, and lets the client handle the disconnect more gracefully.
